jwt:
  secret:
    key: 776974682d7769742d616e642d63616e646f722d616e642d68756d6f722d616e642d656d70617468794c4f5645


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/user?rewriteBatchedStatements=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
cloud:
  aws:
    credentials:
      access-key: { }
      secret-key: {}
    s3:
      bucket: hojin-profile-bucket
    region:
      static: ap-northeast-2